
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gxpdb
    username: root
    password: manish@mysql#123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

app:
  jwt:
    secret: "change-me-super-secret-key-please"
    expirationMs: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

resilience4j:
  circuitbreaker:
    instances:
      notificationClient:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      notificationClient:
        maxAttempts: 3
        waitDuration: 500ms
